version: '3.8'

services:

  grafana:
    image: grafana/grafana:11.0.0-ubuntu
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    depends_on:
      - mysql
    networks:
      custom_network:
        ipv4_address: 172.22.0.2

  mysql:
    image: mysql:8.0
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - custom_network

#  postgres:
#    image: postgres:16-alpine
#    ports:
#      - "13432:5432"
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#
networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24