version: '3.8'

services:

  grafana:
    image: grafana/grafana:11.0.0-ubuntu
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
#    depends_on:
#      - prometheus

  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "13090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml

  prom-node:
    image: prom/node-exporter:v1.8.1
    ports:
      - "13190:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: --path.procfs /host/proc --path.sysfs /host/sys --path.rootfs /rootfs

  loki:
    image: grafana/loki:2.9.8
    ports:
      - "13100:3100"
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    ports:
      - "13080:9080"
    volumes:
      - ~/nginx-the-proxy/data/logs:/var/log/nginx_log
    command: -config.file=/etc/promtail/local-config.yaml
    depends_on:
      - loki

volumes:
  grafana:

