version: '3.7'

services:

  grafana:
    image: grafana/grafana:11.0.0-ubuntu
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - grafana_logs:/var/log:wo
      #      - grafana_proc:/proc
      - grafana_sys:/sys
      - grafana_rootfs:/rootfs
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    depends_on:
      - mysql

  grafana-exporter:
    image: prom/node-exporter:v1.8.1
    volumes:
      #      - grafana_proc:/host/proc
      - grafana_sys:/host/sys:ro
      - grafana_rootfs:/rootfs:ro
    command: --path.sysfs /host/sys --path.rootfs /rootfs
    depends_on:
      - grafana

  mysql:
    hostname: mysql.local.com
    image: mysql:8.0
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  loki:
    image: grafana/loki:2.9.8
    ports:
      - "13100:3100"
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/local-config.debug.yaml

  promtail:
    image: grafana/promtail:3.0.0
    ports:
      - "13080:9080"
    volumes:
      - ./promtail:/etc/promtail
      - ./mysql:/var/log/mysql_logs
      - grafana_logs:/var/log/grafana_logs
      - nginx_logs:/var/log/nginx_log
    command: -config.file=/etc/promtail/local-config.debug.yaml
    depends_on:
      - loki

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "13088:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
  #    network_mode: host

# it is used for cloud
  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "13090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.debug.yml

  prom-node:
    image: prom/node-exporter:v1.8.1
    ports:
      - "13190:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: --path.procfs /host/proc --path.sysfs /host/sys --path.rootfs /rootfs

# it is used for IOT devices
  influxdb:
    image: influxdb:2.7.6-alpine
    ports:
      - "13086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2
# admin: 7hsQKYmfwYzW9ZsD_wCvdJJGwnKdBgoaS4230UZW6dBDb75ScdzOW7HMplXXAAVVnj4i8zww4r3N9RNDtGzmlg==
# read only: ej7vIzJjiAsvpKQY86RorYCSYwWUxMCSz5e1v1z69cBYP7Q9zkwjwN5-oke17KdRkszSJ0j1G4YSQ4xkrP-vAg==

  telegraf:
    image: telegraf:1.30-alpine
    volumes:
      - ./telegraf:/etc/telegraf
    command: --config-directory=/etc/telegraf/telegraf.debug.conf

volumes:
  mysql_logs:
  grafana_logs:
  nginx_logs:
  grafana_proc:
  grafana_sys:
  grafana_rootfs:
  influxdb: