version: '3.7'

services:

  grafana:
    image: grafana/grafana:11.0.0-ubuntu
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - grafana_logs:/var/log:wo
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    depends_on:
      - mysql

  mysql:
    hostname: mysql.local.com
    image: mysql:8.0
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - mysql_logs:/var/log:wo
    environment:
      - MYSQL_ROOT_PASSWORD=root

  loki:
    image: grafana/loki:2.9.8
    ports:
      - "13100:3100"
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    ports:
      - "13080:9080"
    volumes:
      - ./promtail:/etc/promtail
      - mysql_logs:/var/log/mysql_logs:ro
      - grafana_logs:/var/log/grafana_logs:ro
    command: -config.file=/etc/promtail/local-config.yaml
    depends_on:
      - loki

volumes:
  mysql_logs:
  grafana_logs: