

services:

  grafana:
    image: grafana/grafana:11.0.0-ubuntu
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
#    depends_on:
#      - prometheus