server:
  http_listen_port: 9080
  grpc_listen_port: 9097

positions:
  filename: /tmp/positions.yaml

clients:
  - url: 'http://loki:3100/loki/api/v1/push'
#    Can be http://loki.darkinowls.com/loki/api/v1/push

scrape_configs:
  - job_name: single
    static_configs:
      - targets:
          - localhost
        labels:
          job: server_logs
          __path__: /var/log/*log

  - job_name: mysql_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: sql_logs
          __path__: /var/log/mysql_logs/mysql.log

  - job_name: grafana_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: grafana_logs
          __path__: /var/log/grafana_logs/*

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_log
          __path__: /var/log/nginx_log/*log